#!/usr/bin/env node
/**
 * sync-tokens.js
 * Reads tokens.json (Tokens Studio format) and regenerates tokens.css.
 *
 * Workflow:
 *   1. Export updated tokens from Tokens Studio for Figma → replace tokens.json
 *   2. Run: npm run sync-tokens
 *   3. tokens.css is updated and ready for the browser
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const tokens = JSON.parse(readFileSync(join(root, 'tokens.json'), 'utf-8'));

// ── Flat token registry for reference resolution ──────────────────────────────
const registry = {};

function flattenSet(obj, prefix = '') {
  for (const [key, val] of Object.entries(obj)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (val && typeof val === 'object' && 'value' in val) {
      registry[path] = val;
    } else if (val && typeof val === 'object') {
      flattenSet(val, path);
    }
  }
}

for (const [set, val] of Object.entries(tokens)) {
  if (set.startsWith('$')) continue;
  flattenSet(val, set);
}

// ── Reference resolver (returns raw value, resolving chains) ──────────────────
function resolveRaw(value) {
  if (typeof value !== 'string' || !value.includes('{')) return value;
  return value.replace(/\{([^}]+)\}/g, (_, ref) => {
    const token = registry[ref];
    if (!token) return ref;
    return resolveRaw(token.value);
  });
}

// ── Token path → CSS variable name ───────────────────────────────────────────
function pathToVar(ref) {
  if (ref.startsWith('primitives/colors.')) {
    const rest = ref.replace('primitives/colors.', '');
    const parts = rest.split('.');
    return parts.length === 1
      ? `var(--color-${parts[0]})`
      : `var(--color-${parts[0]}-${parts[1]})`;
  }
  if (ref.startsWith('primitives/typography.fontFamily.')) {
    return `var(--font-${ref.replace('primitives/typography.fontFamily.', '')})`;
  }
  if (ref.startsWith('primitives/typography.fontSize.')) {
    return `var(--text-${ref.replace('primitives/typography.fontSize.', '')})`;
  }
  if (ref.startsWith('primitives/typography.fontWeight.')) {
    return `var(--font-weight-${ref.replace('primitives/typography.fontWeight.', '')})`;
  }
  if (ref.startsWith('primitives/typography.lineHeight.')) {
    return `var(--leading-${ref.replace('primitives/typography.lineHeight.', '')})`;
  }
  if (ref.startsWith('primitives/typography.letterSpacing.')) {
    return `var(--tracking-${ref.replace('primitives/typography.letterSpacing.', '')})`;
  }
  if (ref.startsWith('primitives/spacing.')) {
    const k = ref.replace('primitives/spacing.', '').replace('.', '-');
    return `var(--spacing-${k})`;
  }
  if (ref.startsWith('primitives/shadow.')) {
    const name = ref.replace('primitives/shadow.', '');
    return name === 'DEFAULT' ? 'var(--shadow)' : `var(--shadow-${name})`;
  }
  return `var(--${ref.replace(/\//g, '-').replace(/\./g, '-')})`;
}

// Replace {ref} patterns with var(--...) references (for semantic tokens)
function refToVar(value) {
  return value.replace(/\{([^}]+)\}/g, (_, ref) => pathToVar(ref));
}

// ── Output builder ────────────────────────────────────────────────────────────
const lines = [];
const line = (s = '') => lines.push(s);

// ── HEADER ────────────────────────────────────────────────────────────────────
line(`/* ============================================================`);
line(`   OBRA DESIGN SYSTEM — CSS Custom Properties`);
line(`   Auto-generated by scripts/sync-tokens.js — do not edit by hand`);
line(`   Run: npm run sync-tokens`);
line(`   Brand colors: Primary #013229 · Secondary #FFD653 · Intense #61CAA0 · Grey #333333`);
line(`   ============================================================ */`);

// ── COLOR PRIMITIVES ──────────────────────────────────────────────────────────
line();
line(`/* ────────────────────────────────────────`);
line(`   COLOR PRIMITIVES`);
line(`   ──────────────────────────────────────── */`);
line();
line(`:root {`);

const colors = tokens['primitives/colors'] || {};
const paletteOrder = ['primary', 'secondary', 'intense', 'neutral', 'destructive', 'success', 'info'];
const paletteLabel = {
  primary:     'Primary — Forest Green',
  secondary:   'Secondary — Golden Yellow',
  intense:     'Intense — Mint Teal',
  neutral:     'Neutral — Grey',
  destructive: 'Destructive — Red',
  success:     'Success — Green',
  info:        'Info — Blue',
};

for (const palette of paletteOrder) {
  const pal = colors[palette];
  if (!pal || 'value' in pal) continue;
  line();
  line(`  /* ${paletteLabel[palette] || palette} */`);
  for (const [shade, token] of Object.entries(pal)) {
    const raw = resolveRaw(token.value);
    const varName = `--color-${palette}-${shade}:`;
    const note = token.description?.includes('Base') ? ' /* Base */' : '';
    line(`  ${varName.padEnd(30)} ${raw};${note}`);
  }
}

// White and black
if (colors.white) {
  line();
  line(`  /* Base */`);
  line(`  --color-white:                 #FFFFFF;`);
}
if (colors.black) {
  line(`  --color-black:                 #000000;`);
}
line(`}`);

// ── SEMANTIC — LIGHT ──────────────────────────────────────────────────────────
line();
line(`/* ────────────────────────────────────────`);
line(`   SEMANTIC TOKENS — LIGHT MODE (default)`);
line(`   ──────────────────────────────────────── */`);
line();
line(`:root,`);
line(`[data-theme="light"] {`);

const semLight = tokens['semantic/light']?.color || {};
for (const [name, token] of Object.entries(semLight)) {
  const val = token.value.includes('{') ? refToVar(token.value) : token.value;
  const varName = `--${name}:`;
  line(`  ${varName.padEnd(30)} ${val};`);
}
line();
line(`  /* Border radius — ShadCN convention */`);
line(`  --radius: 0.75rem; /* 12px */`);
line();
line(`  /* Semantic radius aliases */`);
const semRadiusLight = tokens['semantic/light']?.radius || {};
for (const [name, token] of Object.entries(semRadiusLight)) {
  const raw = resolveRaw(token.value);
  const val = isNaN(parseFloat(raw)) ? raw : `${parseFloat(raw)}px`;
  line(`  --radius-${name}:              ${val};`);
}
line(`}`);

// ── SEMANTIC — DARK ───────────────────────────────────────────────────────────
line();
line(`/* ────────────────────────────────────────`);
line(`   SEMANTIC TOKENS — DARK MODE`);
line(`   ──────────────────────────────────────── */`);
line();
line(`[data-theme="dark"],`);
line(`.dark {`);

const semDark = tokens['semantic/dark']?.color || {};
for (const [name, token] of Object.entries(semDark)) {
  const val = token.value.includes('{') ? refToVar(token.value) : token.value;
  const varName = `--${name}:`;
  line(`  ${varName.padEnd(30)} ${val};`);
}
line();
line(`  --radius: 0.75rem;`);
line(`}`);

// ── SPACING ───────────────────────────────────────────────────────────────────
line();
line(`/* ────────────────────────────────────────`);
line(`   SPACING`);
line(`   ──────────────────────────────────────── */`);
line();
line(`:root {`);

const spacing = tokens['primitives/spacing'] || {};
for (const [key, token] of Object.entries(spacing)) {
  const cssKey = key.replace('.', '-');
  const varName = `--spacing-${cssKey}:`;
  const val = `${token.value}px`;
  line(`  ${varName.padEnd(22)} ${val};`);
}
line(`}`);

// ── TYPOGRAPHY ────────────────────────────────────────────────────────────────
line();
line(`/* ────────────────────────────────────────`);
line(`   TYPOGRAPHY`);
line(`   ──────────────────────────────────────── */`);
line();
line(`:root {`);

// Brand fonts override tokens.json (which has Inter/system defaults)
line(`  --font-sans: "Unigeo32", ui-sans-serif, system-ui, -apple-system, sans-serif;`);
line(`  --font-mono: "Space Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;`);
line();

const typo = tokens['primitives/typography'] || {};

// Font sizes → rem
for (const [size, token] of Object.entries(typo.fontSize || {})) {
  const rem = `${parseFloat(token.value) / 16}rem`;
  const varName = `--text-${size}:`;
  line(`  ${varName.padEnd(16)} ${rem};   /* ${token.value}px */`);
}
line();

// Font weights
for (const [weight, token] of Object.entries(typo.fontWeight || {})) {
  const varName = `--font-weight-${weight}:`;
  line(`  ${varName.padEnd(26)} ${token.value};`);
}
line();

// Line heights
for (const [lh, token] of Object.entries(typo.lineHeight || {})) {
  const varName = `--leading-${lh}:`;
  line(`  ${varName.padEnd(22)} ${token.value};`);
}
line();

// Letter spacing
for (const [ls, token] of Object.entries(typo.letterSpacing || {})) {
  const varName = `--tracking-${ls}:`;
  line(`  ${varName.padEnd(22)} ${token.value};`);
}
line(`}`);

// ── SHADOWS ───────────────────────────────────────────────────────────────────
line();
line(`/* ────────────────────────────────────────`);
line(`   SHADOWS`);
line(`   ──────────────────────────────────────── */`);
line();
line(`:root {`);

const shadows = tokens['primitives/shadow'] || {};
for (const [name, token] of Object.entries(shadows)) {
  if (name === 'none') continue;
  const varName = (name === 'DEFAULT' ? '--shadow:' : `--shadow-${name}:`);
  line(`  ${varName.padEnd(16)} ${token.value};`);
}
line();
line(`  /* Semantic shadow aliases */`);
const semShadow = tokens['semantic/light']?.shadow || {};
for (const [name, token] of Object.entries(semShadow)) {
  const val = token.value.includes('{') ? refToVar(token.value) : token.value;
  const varName = (name === 'DEFAULT' ? '--shadow-default:' : `--shadow-${name}-alias:`);
  line(`  ${varName.padEnd(22)} ${val};`);
}
line(`}`);

// ── Write output ──────────────────────────────────────────────────────────────
const css = lines.join('\n') + '\n';
writeFileSync(join(root, 'tokens.css'), css, 'utf-8');
console.log('tokens.css regenerated successfully');
